### ISSUE TITLE
Grammar error in English i18n

### ISSUE THREAD

**Issue by synapse709** [wearebraid/vue-formulate-i18n#13]
![CleanShot 2020-05-05 at 12 05 10@2x](https://user-images.githubusercontent.com/4532534/81031862-bd5fd880-8ec8-11ea-99a7-4aaa3cc70514.jpg)

I'm adding a new language and noticed the following line in the `en.js` file:

 /*  Is not a valid date. */
`${s(name)} is not a valid, please use the format ${args[0]}`

Should be either "is not a valid date" or "is not valid"

**Comment by justin-schroeder** [comment]
Thanks @synapse709. Somehow that's been lurking in there for a while and no one noticed — till you! I'm going to merge the fix into master but will wait for other fixes or a new language to publish a patch.
