### ISSUE TITLE
Remove two rollup dependencies

### ISSUE THREAD

**Issue by BjornLuG** [wearebraid/vue-formulate-i18n#9]
Hello, I'm currently using vue-formulate and this is a dependency of it. I noticed this library has a dependency on `@rollup/plugin-buble` and `@rollup/plugin-commonjs` which is odd since they're only used in build environments.

After some digging, I found that `@rollup/plugin-buble` is only used in `build/rollup.config.js` which is only called during `npm run build`. I didn't find any usage for `@rollup/plugin-commonjs` though.

Would be great if `@rollup/plugin-buble` can be moved as a dev dependency and have `@rollup/plugin-commonjs`  removed to clean things up.

**Comment by justin-schroeder** [comment]
You are 100% correct. Grrr, thats a dumb mistake on my part...I'll get a patch going here.

**Comment by justin-schroeder** [comment]
Ok this is fixed in `v1.3.3.` and also patched into `vue-formulate` proper with `v2.2.6`. Thanks!
